name: fit3d
channels:
  - conda-forge
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.24
  - pytorch>=2.0.1
  - cudatoolkit>=11.7
  - einops>=0.6
  - tqdm>=4.65
  - joblib>=1.3
  - chumpy>=0.70
  - pip:
    - h5py>=3.8.0
    - smplx>=0.1.28